// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:b6fd46fb-f7fb-4f52-a0e6-28ab25c6e539",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_QCIIlfLTL",
    "aws_user_pools_web_client_id": "7b4d4gjeek2mobqqpfht2gtm8p",
    "oauth": {},
    "aws_user_files_s3_bucket": "authexp689b384788284696b2f6d96eda3b4247-testbis",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
